### ISSUE TITLE
Misaligned pointer dereference in debug mode

### ISSUE THREAD

**Issue by Payn** [ohadravid/netstat2-rs#8]
let af_flags = AddressFamilyFlags::IPV4 | AddressFamilyFlags::IPV6; 
    let proto_flags = ProtocolFlags::TCP | ProtocolFlags::UDP; 
    let sockets_info = get_sockets_info(af_flags, proto_flags).unwrap();

this code causes panic:
'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x7f598f31e48c', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/netstat2-0.9.1/src/integrations/linux/netlink_iterator.rs:192:24

Doesn't happen in release mode.

Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-1160.92.1.el7.x86_64

**Comment by ohadravid** [comment]
I think the problem is that the line (`netlink_iterator.rs:192`)

```
let tcpi = &*(RTA_DATA!(attr) as *const tcp_info);
```

should actually be [`read_unaligned`](https://doc.rust-lang.org/stable/std/ptr/fn.read_unaligned.html#) (I skimmed the docs but couldn't find if this is expected or not, but I assume you do get correct info when running in release so the address calculation is correct).

@Payn I would appreciate if you could test this and maybe open a PR? 🙏🙂

**Comment by Payn** [comment]
@ohadravid so i created a PR with the change, not sure if done correctly, but it works now in debug mode.
https://github.com/ohadravid/netstat2-rs/pull/10

**Comment by ohadravid** [comment]
Fixed as part of #17
